Improvements around forum favoriting
challfry/swiftarr pull request #15
Opened 2022-01-16 21:44 UTC by cohoe

* Fix issue preventing forum favoriting from working and silence a particular variety of JS warning.
* Automatically favorite created forums. Eventually posts in favorited forums should generate a type of notification, but we aren't there yet.
* Add thread count of favorited forums to main page.
* Remove non-printing characters that are invisible on Apple devices.

2022-01-17 22:06 UTC, cohoe commented
Closing so I can push more things.

2022-01-23 16:46 UTC, challfry requested changes
I'd need some convincing that auto-favoriting forums the user creates is something worthwhile to users, and even more convincing that showing favorite counts adds enough value to justify an extra API call. 

Adding an API call to gather event locations is a good change, although I worry about how organized the source data for 2022 may be. The 2020 schedule.ics was pretty clean; in previous years there were often multiple spellings of the same location or punctuation differences in a location name. And, due to how the events page works, the locations call may not make sense for the web client (see comments on this)--although I want to be clear that the locations *dropdown* UI is cool.

Anyway, if you feel I'm wrong or really like your changes just comment back about why.

2022-01-23 16:46 UTC, challfry commented on Sources/App/Site/SiteEventsController.swift
> +			let locations = try locationResponse.content.decode([EventLocation].self)
What if instead of calling /locations here we were to build a list of locations from the events response? 

A bit of background. Instead of getting all the events in the schedule when the user goes to /events, the site pages just retrieve either one day's events or events matching a text filter. The filter controls on the page then filter the result set by not showing API results that don't match the filters. So the page gets a subset of all events and then the filter controls let you see a subset of that subset.

What we should *probably* do at some point is change EventData to remove isFavorite. This would allow us to turn on response caching for /api/v3/events when requesting all events (the response when returning all events is ~230K, not huge by internet standards but the largest response size in the API ignoring degenerate cases). 

Anyway, back to building a locations list from the events response subset. There's a lot of locations, making for a big menu popup. Many of the location values filter out all events, showing an empty list. Building a set of locations from the returned events list would improve both of these issues. For that matter, doing this might improve the Event Type dropdown as well.

2022-01-23 16:46 UTC, challfry commented on Sources/App/Site/SiteForumController.swift
> +			let favoriteForums = try countResponse.content.decode(ForumSearchData.self)
Hmm. Querying for the list of favorite forums just to grab their count and display it seems suboptimal, especially on a page that's going to get accessed a lot where we're trying to keep the number of sql queries low and maximize for response time. And, like in my other comment, this is all to tell the user how many times they clicked the 'favorite' button on a forum, which I don't see as a high-value piece of information for them.

I'd need some convincing this is a good change is what I'm saying.

2022-01-23 16:46 UTC, challfry commented on Sources/App/Controllers/ModerationController.swift
> +				}
Oh hey. And, I realized that private seamails now show the 'report' button that's only meant for LFGs. That's a bug. Gah.

2022-01-23 17:15 UTC, cohoe commented on Sources/App/Controllers/ModerationController.swift
> +				}
Ah ha.... that makes more sense. Since seamails are not intended to get moderated I can eliminate all of this change. I'll drop the button (and maybe add a `guard` in the API call to prevent seamails from getting moderated in the first place) in another PR.

2022-01-23 17:15 UTC, cohoe commented on Sources/App/Controllers/UserController.swift
> +				.unwrap(orReplace: Barrel(ownerID: userID, barrelType: .keywordAlert)).flatMap { barrel in
I saw your notes on https://github.com/challfry/swiftarr/issues/2. Given the amount of effort needed there I doubt we'll get to it before the '22 boat. At least doing the `orReplace()` method prevents the app from returning an error.

 I'd be concerned with making Redis the source of truth for anything given we primarily think about it as a cache. But this can be a philosophical discussion for another day.

2022-01-23 17:19 UTC, cohoe commented on Sources/App/Resources/Views/Forums/forumCategories.html
> +								</div>
"That is a lucid, well thought-out, intelligent objection."

It even runs counter to my opinions on favoriting forums described above/below.

2022-01-23 17:20 UTC, cohoe commented on Sources/App/Site/SiteForumController.swift
> +			let favoriteForums = try countResponse.content.decode(ForumSearchData.self)
This has been deprecated per above comments.

2022-01-23 17:34 UTC, cohoe commented on Sources/App/Controllers/ForumController.swift
> +						// Original request for creation of the forum
The case I recall having from '20 boat was this: When I created a thread, I wanted to be notified whenever anyone posted to that thread. I don't recall if favorites were a thing in past-Twitarr but I remember having to manually find the thread and refresh to see if anyone had posted (particularly relevant for question-based threads such as "Where can I get a yipyip?"). 

As it stands currently I feel that Swiftarr lets users create a glorified bookmark of useful threads which already solves a part of the situation described. However I think it's a worthy goal to generate new/unread notifications for posts in favorite threads for those who want the increased visibility. I had a brainwave around https://github.com/challfry/swiftarr/pull/15/files#diff-76fa5ced907b797092670d8fdb6134e7bc16c83832eeedc0b45405c199edaf6dR678 about maybe making this an opt-in/out checkbox when creating the thread, so perhaps that would address the POLA concern?

An alternative for this case would be to opt in/out of notifications for "threads you created" specifically. Though at that point the notification behavior would effectively have to be duplicated for both created and favorited threads which feels like more effort than simply marking createds as favorites to take advantage of their notification system.

2022-01-23 17:44 UTC, cohoe commented on Sources/App/Site/SiteEventsController.swift
> +			let locations = try locationResponse.content.decode([EventLocation].self)
I intentionally made Locations a bit overcomplicated at this point to leave the possibility open for future enhancements and data around them. For example - linking to a ship map (location stored as x,y coordinates for an image), queries for "whats near me", "what is the closest bar", etc. But perhaps all of that would be better suited for a quasi-static set of location seeds that don't depend on the free-form ICS data? Regardless it could probably at least be cached since I suspect there isn't much change in the result set after the event import.

Not providing an API endpoint also means any client would be on their own for figuring out locations. I barely knew what the ecosystem looked like in '20 and it seems that interest in making native-apps has been waning (though that might also be :wave: everything :wave: fatigue). I agree that building locations from the events response could probably be a thing, but I believe that being declarative about it might make our lives easier down the road.

I suppose another pertinent question here is: Given the heavy usage of Sched, is it worth us even managing events at all? Should we 302 over to Sched and be done with it? In '20 we were able to get Sched without a WiFi package on the boat.

2022-01-25 19:55 UTC, challfry commented on Sources/App/Controllers/ForumController.swift
> +						// Original request for creation of the forum
Currently there aren't notifications for new posts in forums you've favorited nor for forums you've created. And, in an attempt to make the notification call not be a strain on the server, most of the notification count values in UserNotificationData are cached at post creation time. Otherwise, in order to gather all the counts we'd need to return, we'd need to query all the twartts, all the forums, the active announcements, all the messages in all seamail and LFG threads that have the user as a member, plus a few more things if the user is a mod. And, several of those queries would need to post-process the results to parse exact username mentions (SQL's `LIKE` isn't precise enough). The notification endpoint is a high-traffic call that should return quickly.

So--adding code to provide notifications on posts to forums the user created wouldn't be too bad. Off the top of my head, a Redis set with key "<userID>-createdForums" (or similar) where each member of the set is the UUID of a forum the user created would work. Whenever anyone makes a forum post we'd get the forum creator's userID (which we already have; wouldn't need a new query) and add the forum's UUID to that user's set of forums they created that have new messages. When a user views a forum (in API terms, calls /api/v3/forum/:forum_ID), if the user is the creator of the forum we clear the forum's UUID from the set. The notification call just asks Redis for the ordinality of the set and returns that in a new "createdForumWithNewPostCount" field (maybe workshop the name a bit).

Doing the same thing for favorited posts is harder, because of Barrels. Since Barrels are "I'm putting a key-value store inside this here relational database" there isn't an efficient way to get from a forumID to all of the users who have favorited that forum. It'd be easier and more performant if Forum Favorites were a pivot between users and forums. Once that bit is done the rest of implementing notification for posts in favorited forums would work the same as I described above, except you'd have to loop through all the users who've favorited the forum.

2022-01-25 20:20 UTC, challfry commented on Sources/App/Site/SiteEventsController.swift
> +			let locations = try locationResponse.content.decode([EventLocation].self)
The 2020 ics schedule file is pretty clean, but IIRC in previous years there were lots of instances where events would use slightly different names for the same place. And, given the rather high chance we'll need to make a mid-voyage schedule change for one reason or another this year, I'm really leery of making a design where we might have to manually clean up the ics we get from Sched before applying it. I don't want to be editing the schedule file in BBEdit while on the boat.

But, if we could figure out a way to make locations more canonical we could make them a DB table with IDs, attach map coordinates to them, add a URL query to /api/v3/events to filter by location (where you'd provide the ID instead of the location's long name), bunch of stuff.

As to having a schedule on the website and in the API, my opinion is that we can do better than Sched's website. Not that we can out-program a team of engineers that are doing their day job, but we can make something specifically for Boat while Sched cannot. My Kraken client app caches schedule data allowing for offline access and it shows where an event is happening on a deck map. Both Kraken and the website link each event with its own forum thread, which ... maybe sched.com does this too, but I can't even tell.

2022-01-25 20:25 UTC, challfry commented on Sources/App/Controllers/UserController.swift
> +				.unwrap(orReplace: Barrel(ownerID: userID, barrelType: .keywordAlert)).flatMap { barrel in
Gah, I've forgotten how Github PRs work. This should have just been a separate comment instead of being part of the review.

2022-01-25 22:36 UTC, challfry commented on Sources/App/Controllers/ForumController.swift
> +						// Original request for creation of the forum
Sorry, I keep getting off track while writing review notes. Adding code so that the notification endpoint returns info on new posts in both favorited and created forums would be useful, but if we did that I'd definitely suggest that those be two separate numbers returned by the notification endpoint, which means we wouldn't need to have this code that auto-favorited forums upon creation in order to get notified of new posts--any forum you created would provide notifications when new posts happened.

If we don't want to notify on every forum thread the user creates and only have notifications for favorites, I'd still prefer that we don't auto-favorite upon creation; users would opt in (by favoriting) to get the notification behavior.

2022-01-28 04:15 UTC, cohoe commented on Sources/App/Controllers/ForumController.swift
> +						// Original request for creation of the forum
All good. I didn't realize the time crunch we were under. You make good points and we have other fish to fry so I'll retract those changes.

2022-01-28 04:18 UTC, cohoe commented on Sources/App/Site/SiteEventsController.swift
> +			let locations = try locationResponse.content.decode([EventLocation].self)
I think if we ever get to a state where we don't have to munge an ICS that'd definitely put us in a better state to support something like this. Interactive map was the long-term goal for this to support and I have some other more appropriate ways in which to implement such helpers for the backend. So like above, we'll just shelve it.

2022-01-28 04:28 UTC, cohoe commented
I've retracted the big things we've discussed since there's no way we'll get to them in time for '22. Hopefully the smaller changeset here is more manageable.

2022-01-29 00:41 UTC, merged