Enable serving static arbitrary content
challfry/swiftarr pull request #22
Opened 2022-02-03 04:00 UTC by cohoe

This sets us up to easily serve random static content (such as the KrakenPost list). Any content can be dynamically added to the server in the appropriate directory and immediately be available.

2022-02-03 20:23 UTC, challfry requested changes

2022-02-03 20:23 UTC, challfry commented on Sources/App/configure.swift
> +	app.logger.notice("Serving static content from \(app.directory.publicDirectory).")
Hey, Grant. I'm awake now, really. 

FileMiddleware checks eTags and will respond with NotModified, but doesn't set cache-control, which we probably show for static files. That was the main reason for creating SiteFileController and using it instead of FileMiddleware. 

A freshness interval other an 24 hours may be appropriate for this purpose, but we should support Joey's thing with a new call in SiteFileController.

2022-02-03 23:55 UTC, cohoe commented on Sources/App/configure.swift
> +	app.logger.notice("Serving static content from \(app.directory.publicDirectory).")
That's a good reason. I've updated the PR to add support for a `Assets/public` directory instead. We lose the dynamic adding of random files without a restart but maybe in the future that can be fixed.

2022-02-05 19:14 UTC, challfry approved these changes
Groovy.

2022-02-05 19:14 UTC, merged